#!/bin/bash

##
# @file
# OpenSourcery Drupal Deployment Script
#
# @todo This currently won't work for initial deployment to a Drupal
# host. Several things still need to be done manually the first time
# around--creating directory structure: releases, shared/files,
# modifying/uploading settings.php

# Change $SUBDOMAIN accordingly, e.g. <mountain name>
# Rather than set $USER, use the user we were run as.
SUBDOMAIN=demo
HOST=gargravarr
INSTALLROOT=/var/www/$SUBDOMAIN
INSTALLPROFILE=os_project

# Flag to disable running of `drush site-install`.
#NOSITEINSTALL=1

# Branch to deploy from
BRANCH=.

##### Things below here generally won't need to be changed #####

# If SUBDOMAIN isn't set, INSTALLROOT would become /var/www// and we'd blow
# away the permissions of every test host on the test server.
if [ -z "$SUBDOMAIN" ]; then
  echo "ERROR: You must set SUBDOMAIN (within $0) before running this script."
  exit 1
fi

if [ ! -d ./drupal ]; then
  echo "ERROR: ./drupal directory does not exist; nothing to deploy."
  exit 1
fi

# Test that this drush alias exists.
ALIAS=`drush sa @$SUBDOMAIN --component=root`
if [ -z "$ALIAS" ]; then
  echo "Didn't find a drush alias for $SUBDOMAIN"
  exit 1
fi

# Deploy into the releases directory.
TIMESTAMP=`date +%Y_%m_%d__%H_%M_%S`

# Add -L to copy symlinks' referent files, so that we'll bring along our install profile
cp -Rp $INSTALLROOT/current/ $INSTALLROOT/releases/$TIMESTAMP
rsync -LazC --exclude=sites/all/files --exclude=sites/default/files --exclude=sites/default/settings.php --exclude=backup $BRANCH/drupal/ $INSTALLROOT/releases/$TIMESTAMP/

# Create links to settings and files.
if [ ! -h $INSTALLROOT/releases/$TIMESTAMP/sites/default/files ]; then
  ln -s $INSTALLROOT/shared/files $INSTALLROOT/releases/$TIMESTAMP/sites/default/files
fi
if [ ! -h $INSTALLROOT/releases/$TIMESTAMP/sites/default/settings.php ]; then
  ln -s $INSTALLROOT/shared/settings.php $INSTALLROOT/releases/$TIMESTAMP/sites/default/settings.php
fi

# Remove old release link and link the new version.
if [ -h $INSTALLROOT/current ]; then
  rm $INSTALLROOT/current
fi
ln -s $INSTALLROOT/releases/$TIMESTAMP $INSTALLROOT/current

# Run site install unless disabled.
if [ -z $NOSITEINSTALL ]; then
  drush @$SUBDOMAIN site-install -y $INSTALLPROFILE
  if [ $? -gt 0 ]; then
    exit 1
  fi
fi

# Clear caches.
drush @$SUBDOMAIN cc all

# Run any update hooks.
drush @$SUBDOMAIN updatedb -y

# TODO this is a bug in drush: need to manually remove command cache,
# or the features command isn't found until after the bash script
# completes.
rm -rf ~/.drush/cache/default/*

# Features revert.
drush @$SUBDOMAIN fra -y

# Clear caches.
drush @$SUBDOMAIN cc all

# Remove all but the last 4 builds in the releases directory.
cd $INSTALLROOT/releases
sudo rm -rf `ls -1r | tail -n +5`
cd -

echo "Deployment complete"
