#!/bin/bash

# $Id$

##
# @file
# OpenSourcery Drupal Deployment Script
#
# @todo This currently won't work for initial deployment to a Drupal
# host. Several things still need to be done manually the first time
# around.

# Deploy to Canvas Dreams
USER=
HOST=
INSTALLROOT=/home/$USER/os_app
DOCUMENTROOT=/home/$USER/public_html

##### Things below here generally won't need to be changed #####

# Initial run? Set up some stuff.
if [[ "$1" = "--init" ]]; then
  ssh $USER@$HOST mkdir -p $INSTALLROOT/shared/files
  scp ./drupal/sites/default/default.settings.php $USER@$HOST:$INSTALLROOT/shared/settings.php
  ssh $USER@HOST chmod 400 $INSTALLROOT/shared/settings.php
  # @todo: Archive existing "public_html" and create initial dummy symlink
fi

TIMESTAMP=`date +%Y_%m_%d__%H_%M_%S`

# Values below here shouldn't need to be modified for standard OS Drupal deployments

mkdir /tmp/$TIMESTAMP

# Add -L to copy symlinks' referent files, so that we'll bring along our install profile
rsync -LavzC --exclude=sites/default/files --exclude=sites/default/settings.php --exclude=backup ./drupal/ /tmp/$TIMESTAMP/

# We don't automate deploying files.
rm -Rf /tmp/$TIMESTAMP/sites/default/files

# Create links to settings and files. This is done locally, prior to upload,
# even though locally they are broken links.
ln -s $INSTALLROOT/shared/files /tmp/$TIMESTAMP/sites/default/files
ln -s $INSTALLROOT/shared/settings.php /tmp/$TIMESTAMP/sites/default/settings.php

ssh $USER@$HOST cp -Rp $DOCUMENTROOT/ $INSTALLROOT/releases/$TIMESTAMP
rsync -avzC --delete /tmp/$TIMESTAMP/ $USER@$HOST:$INSTALLROOT/releases/$TIMESTAMP/

# Change group to PHP's user
#ssh $USER@$HOST chgrp -R www-data $INSTALLROOT

# Remove old release link and link the new version
ssh $USER@$HOST "rm $DOCUMENTROOT; ln -s $INSTALLROOT/releases/$TIMESTAMP $DOCUMENTROOT"

# Clean up local machine
rm -Rf /tmp/$TIMESTAMP
