#!/bin/bash
if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
  echo "Usage: $0 <machine_name> <Project Name> <Project Description>"
  echo "Ex: $0 client_xyz \"Web app ABC\" \"Client XYZ's ABC app enables users to browse a database of records.\""
  exit 1
fi

if [ ! -d os_project ]; then
  echo "Error: Cannot find os_project directory"
  exit 2
fi

NEW="$1"
PROJECTNAME="$2"
DESCRIPTION="$3"
FILES="os_project.info os_project.install os_project.make os_project.profile"
SEDFLAGS="-i.orig"

# rebuild script
sed -e "s/PROFILE=\"os_project\"/PROFILE=\"$NEW\"/" $SEDFLAGS rebuild.sh
sed -e "s/PROJECT/$PROJECTNAME/" $SEDFLAGS rebuild.sh

# deploy script
sed -e "s/INSTALLPROFILE=os_project/INSTALLPROFILE=$NEW/" $SEDFLAGS deploy_to_test

mkdir $NEW
cp os_project/os_project.* $NEW/
cp os_project/*make $NEW/
cd $NEW
sed -e "s/os_project/$NEW/" $SEDFLAGS $FILES
sed -e "s/PROJECTNAME/$PROJECTNAME/" $SEDFLAGS $FILES
sed -e "s/DESCRIPTION/$DESCRIPTION/" $SEDFLAGS $FILES
mv os_project.info    $NEW.info
mv os_project.install $NEW.install
mv os_project.make    $NEW.make
mv os_project.profile $NEW.profile
rm *.orig
cd ..
