<?php

// $Id: os_custom.module 887 2009-09-24 15:51:14Z jhedstrom $

/**
 * @file
 * OpenSourcery base customizations.
 */

/**
 * Implementation of hook_form_alter().
 *
 * - Sets the revisions as enabled for new content types.
 */
function os_custom_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'node_type_form':
      if (!isset($form['#node_type']->orig_type)) {
        $options = array();
        // Set to published by default.
        $options[] = 'status';
        // Enable revisions by default.
        $options[] = 'revision';
        $form['workflow']['node_options']['#default_value'] = $options;
      }
      break;
  }
}

/**
 * Implementation of hook_imagecache_default_presets().
 */
function os_custom_imagecache_default_presets() {
  module_load_include('imagecache.inc', 'os_custom');
  return _os_custom_imagecache_default_presets();
}

/**
 * Implementation of hook_strongarm().
 */
function os_custom_strongarm() {

  // Set front page here.
  // $conf['site_frontpage'] = '';

  if (module_exists('path_redirect')) {
    // Pathauto.
    $conf['pathauto_update_action'] = 3;
  }

  return $conf;
}

/**
 * Preprocess page variables.
 */
function os_custom_preprocess_page(&$vars) {
  if (isset($vars['footer_message'])) {
    // Replace @year with current year.
    $vars['footer_message'] = str_replace('@year', date('Y'), $vars['footer_message']);
  }
}