<?php
/**
 * @file
 * Main installation logic for PROJECTNAME.
 */

!function_exists('profiler_v2') ? require_once('libraries/profiler/profiler.inc') : FALSE;
profiler_v2('os_project');

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function os_project_install() {
  // Enable the admin theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'seven')
    ->execute();
}
