<?php
/**
 * @file
 * Overrides for various features to work on OpenSourcery testing
 * infrastructure.
 */

/**
 * Apache Solr/tomcat6 port on gargravarr.
 */
define('OS_TESTING_SOLR_PORT', 8089);

/**
 * Regex to match virtual host on gargravarr.
 */
define('OS_TESTING_HOST_REGEX', '#(.*)\.opensourcery\.com$#');

/**
 * Implements hook_apachesolr_environments_alter().
 *
 * Override the Solr url when on gargravarr to use proper search index. Note
 * that this only works if the default index uses the default machine name of
 * `solr`.
 */
function os_testing_apachesolr_environments_alter(&$environments) {
  if (isset($environments['solr']) && $host = _os_testing_is_test_host()) {
    $solr_url = 'http://localhost:' . OS_TESTING_SOLR_PORT . '/solr/' . $host;
    $environments['solr']->url = $solr_url;
  }
}

/**
 * Implements hook_default_search_api_server_alter().
 *
 * Override the Solr server options when on gargravarr. Note that this assumes
 * the default server machine name of `default`.
 */
function os_testing_default_search_api_server_alter(array &$defaults) {
  if (isset($defaults['default']) && $host = _os_testing_is_test_host()) {
    $defaults['default']->options['host'] = 'localhost';
    $defaults['default']->options['port'] = OS_TESTING_SOLR_PORT;
    $defaults['default']->options['path'] = '/solr/' . $host;
    $defaults['default']->options['http_user'] = '';
    $defaults['default']->options['http_pass'] = '';
  }
}

/**
 * Implements hook_strongarm_alter().
 *
 * Setup Apache Tika path if this site is using apachesolr attachments.
 */
function os_testing_strongarm_alter(&$variables) {
  if (_os_testing_is_test_host()) {
    if (isset($variables['apachesolr_attachments_tika_jar'])) {
      $variables['apachesolr_attachments_tika_jar']->value = 'tika-app-1.3.jar';
    }
    if (isset($variables['apachesolr_attachements_tika_path'])) {
      $variables['apachesolr_attachments_tika_path']->value = '/usr/local/lib/apache-tika';
    }
    if (isset($variables['search_api_attachments_tika_jar'])) {
      $variables['search_api_attachments_tika_jar']->value = 'tika-app-1.3.jar';
    }
    if (isset($variables['search_api_attachments_tika_path'])) {
      $variables['search_api_attachments_tika_path']->value = '/usr/local/lib/apache-tika';
    }
  }
}

/**
 * Helper function to determine if running on a test host.
 *
 * @return string
 *   Name of the virtual host or FALSE if not running on a test host.
 */
function _os_testing_is_test_host() {
  $host = FALSE;

  if (isset($_SERVER['HTTP_HOST']) && preg_match(OS_TESTING_HOST_REGEX, $_SERVER['HTTP_HOST'], $match)) {
    $host = $match[1];
  }

  return $host;
}
