<?php

// $Id: os_help.module 878 2009-08-27 21:25:19Z jhedstrom $

/**
 * OpenSourcery Inline Help module.
 */

function os_help_step_form(&$element, $form_id, $callback) {
    foreach (element_children($element) as $child) {
      os_help_step_form($element[$child], $form_id . ':' . $child, $callback);
    }
    $callback($element, $form_id);
}

/**
 * Implementation of hook_form_alter().
 */
function os_help_form_alter(&$form, $form_state, $form_id) {
  os_help_step_form($form, $form_id, 'os_help_help_link');
  $form['#description'] = isset($form['#description']) ? os_help_get_from_key('form', $form_id) . ' ' . $form['#description'] : os_help_get_from_key('form', $form_id);
}

function os_help_get_from_key($key) {
  static $helpkeys = array();

  if (empty($helpkeys)) {
    // Loop through types that have field_inline_images attached and enable help.
    $types = node_get_types();
    foreach ($types as $type) {
      if ($field = content_fields('field_inline_images', $type->type)) {
        $helpkeys[$type->type . '_node_form:field_inline_images:0'] = array(
          'module' => 'os_help',
          'file' => 'Uploading--Inserting-and-Scaling-Images'
        );
      }
    }
  }

  return isset($helpkeys[$key]) ? $helpkeys[$key] : FALSE;
}

function os_help_help_link(&$element, $form_id) {
  if (isset($element['#type']) && !in_array($element['#type'], array('button', 'image_button', 'submit', 'markup', 'token', 'hidden', 'form', 'value', 'weight'))) {
    if ($result = os_help_get_from_key($form_id)) {
      $link = theme('advanced_help_topic', $result['module'], $result['file']);
      if ($element['#type'] == 'fieldset') {
        drupal_add_css(drupal_get_path('module', 'os_help') . '/os_help.css');
        $link = preg_replace('/class="(.+?)"/', 'class="\1 os_help-nofloat"', $link);
      }
      $element['#description'] = isset($element['#description']) ? $link . ' ' . $element['#description'] : $link;
    }
  }
}

